# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f096074e471bcf5fda4692b718cfa2301b632de3a7196a6bdd44eaae0943a79e8c522d4185d90e23287fd5600267e25bbe127baea1a2107fb8e998652ec4f051

test:
  secret_key_base: dde4566e31166c440d5aea76b26846b726c30be572011364fb68124f84f6c242ccf62167650553a45b4061e21058fdd1b8331ba50f47f647f1ada8d7aab4c6cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
